### ISSUE TITLE
完美闪退。。。

### ISSUE THREAD

**Issue by hzl2010** [BecodReyes/V4W-Patcher-CHS#1]
弹框一秒，然后就没了。。。
是解压在哪里都可以吗？还是要解压在v4w目录里？

**Comment by hzl2010** [comment]
我去看了原版，能正常运行，就是没中文。这个和原版有啥区别？

**Comment by Becods** [comment]
请连同windows版本一起报告
暂时没测试更多版本
等待更新

**Comment by hzl2010** [comment]
win10专业版 2004 版本号19041.264。
原版能正常运行。这个汉化版不行。
还有原版也更新了，这个还没更新

**Comment by Becods** [comment]
已更新，请重新下载最新版本并重试一次

**Comment by hzl2010** [comment]
不闪退了。就是弹了一堆什么系统找不到指定路径，然后过了几秒自动关掉了。
还是不行。原版还是没问题，打开能正常显示。

**Comment by Crystal-RainSlide** [comment]
@BecodReyes 把文件的换行符设成 CRLF，并且把 Git 的换行符设置为原样提交。
